import { ThemeProvider } from "@/context/theme-provider";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";

const dm_sans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Squeezy Auth App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-background ${dm_sans.className} antialiased`}
        suppressHydrationWarning={true}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem={false}
            disableTransitionOnChange
          >
            {children}
            {/* //toaster lib here */}
          </ThemeProvider>
      </body>
    </html>
  );
}
